#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="master")]
	public partial class StudentDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAttendanceStud(AttendanceStud instance);
    partial void UpdateAttendanceStud(AttendanceStud instance);
    partial void DeleteAttendanceStud(AttendanceStud instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertStudent(Student instance);
    partial void UpdateStudent(Student instance);
    partial void DeleteStudent(Student instance);
    partial void InsertStudentSkupina(StudentSkupina instance);
    partial void UpdateStudentSkupina(StudentSkupina instance);
    partial void DeleteStudentSkupina(StudentSkupina instance);
    partial void InsertTaskTemplate(TaskTemplate instance);
    partial void UpdateTaskTemplate(TaskTemplate instance);
    partial void DeleteTaskTemplate(TaskTemplate instance);
    partial void InsertActivityTemplate(ActivityTemplate instance);
    partial void UpdateActivityTemplate(ActivityTemplate instance);
    partial void DeleteActivityTemplate(ActivityTemplate instance);
    partial void InsertEmailTemplate(EmailTemplate instance);
    partial void UpdateEmailTemplate(EmailTemplate instance);
    partial void DeleteEmailTemplate(EmailTemplate instance);
    partial void InsertActivity(Activity instance);
    partial void UpdateActivity(Activity instance);
    partial void DeleteActivity(Activity instance);
    partial void InsertTask(Task instance);
    partial void UpdateTask(Task instance);
    partial void DeleteTask(Task instance);
    #endregion
		
		public StudentDBDataContext() : 
				base(global::CSAS.Properties.Settings.Default.masterConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StudentDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudentDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudentDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudentDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AttendanceStud> AttendanceStuds
		{
			get
			{
				return this.GetTable<AttendanceStud>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Student> Students
		{
			get
			{
				return this.GetTable<Student>();
			}
		}
		
		public System.Data.Linq.Table<StudentSkupina> StudentSkupinas
		{
			get
			{
				return this.GetTable<StudentSkupina>();
			}
		}
		
		public System.Data.Linq.Table<TaskTemplate> TaskTemplates
		{
			get
			{
				return this.GetTable<TaskTemplate>();
			}
		}
		
		public System.Data.Linq.Table<ActivityTemplate> ActivityTemplates
		{
			get
			{
				return this.GetTable<ActivityTemplate>();
			}
		}
		
		public System.Data.Linq.Table<EmailTemplate> EmailTemplates
		{
			get
			{
				return this.GetTable<EmailTemplate>();
			}
		}
		
		public System.Data.Linq.Table<Activity> Activities
		{
			get
			{
				return this.GetTable<Activity>();
			}
		}
		
		public System.Data.Linq.Table<Task> Tasks
		{
			get
			{
				return this.GetTable<Task>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AttendanceStud")]
	public partial class AttendanceStud : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _Date;
		
		private string _Status;
		
		private int _IDSkupina;
		
		private string _Type;
		
		private System.Nullable<int> _IDStudent;
		
		private int _IdAttendance;
		
		private EntityRef<Student> _Student;
		
		private EntityRef<StudentSkupina> _StudentSkupina;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnIDSkupinaChanging(int value);
    partial void OnIDSkupinaChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnIDStudentChanging(System.Nullable<int> value);
    partial void OnIDStudentChanged();
    partial void OnIdAttendanceChanging(int value);
    partial void OnIdAttendanceChanged();
    #endregion
		
		public AttendanceStud()
		{
			this._Student = default(EntityRef<Student>);
			this._StudentSkupina = default(EntityRef<StudentSkupina>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(15)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSkupina", DbType="Int NOT NULL")]
		public int IDSkupina
		{
			get
			{
				return this._IDSkupina;
			}
			set
			{
				if ((this._IDSkupina != value))
				{
					if (this._StudentSkupina.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDSkupinaChanging(value);
					this.SendPropertyChanging();
					this._IDSkupina = value;
					this.SendPropertyChanged("IDSkupina");
					this.OnIDSkupinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDStudent", DbType="Int")]
		public System.Nullable<int> IDStudent
		{
			get
			{
				return this._IDStudent;
			}
			set
			{
				if ((this._IDStudent != value))
				{
					if (this._Student.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDStudentChanging(value);
					this.SendPropertyChanging();
					this._IDStudent = value;
					this.SendPropertyChanged("IDStudent");
					this.OnIDStudentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAttendance", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdAttendance
		{
			get
			{
				return this._IdAttendance;
			}
			set
			{
				if ((this._IdAttendance != value))
				{
					this.OnIdAttendanceChanging(value);
					this.SendPropertyChanging();
					this._IdAttendance = value;
					this.SendPropertyChanged("IdAttendance");
					this.OnIdAttendanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_AttendanceStud", Storage="_Student", ThisKey="IDStudent", OtherKey="Id", IsForeignKey=true)]
		public Student Student
		{
			get
			{
				return this._Student.Entity;
			}
			set
			{
				Student previousValue = this._Student.Entity;
				if (((previousValue != value) 
							|| (this._Student.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student.Entity = null;
						previousValue.AttendanceStuds.Remove(this);
					}
					this._Student.Entity = value;
					if ((value != null))
					{
						value.AttendanceStuds.Add(this);
						this._IDStudent = value.Id;
					}
					else
					{
						this._IDStudent = default(Nullable<int>);
					}
					this.SendPropertyChanged("Student");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StudentSkupina_AttendanceStud", Storage="_StudentSkupina", ThisKey="IDSkupina", OtherKey="Id", IsForeignKey=true)]
		public StudentSkupina StudentSkupina
		{
			get
			{
				return this._StudentSkupina.Entity;
			}
			set
			{
				StudentSkupina previousValue = this._StudentSkupina.Entity;
				if (((previousValue != value) 
							|| (this._StudentSkupina.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StudentSkupina.Entity = null;
						previousValue.AttendanceStuds.Remove(this);
					}
					this._StudentSkupina.Entity = value;
					if ((value != null))
					{
						value.AttendanceStuds.Add(this);
						this._IDSkupina = value.Id;
					}
					else
					{
						this._IDSkupina = default(int);
					}
					this.SendPropertyChanged("StudentSkupina");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Meno;
		
		private string _Heslo;
		
		private string _Email;
		
		private string _ApiKey;
		
		private EntitySet<StudentSkupina> _StudentSkupinas;
		
		private EntitySet<ActivityTemplate> _ActivityTemplates;
		
		private EntitySet<EmailTemplate> _EmailTemplates;
		
		private EntitySet<Activity> _Activities;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMenoChanging(string value);
    partial void OnMenoChanged();
    partial void OnHesloChanging(string value);
    partial void OnHesloChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnApiKeyChanging(string value);
    partial void OnApiKeyChanged();
    #endregion
		
		public User()
		{
			this._StudentSkupinas = new EntitySet<StudentSkupina>(new Action<StudentSkupina>(this.attach_StudentSkupinas), new Action<StudentSkupina>(this.detach_StudentSkupinas));
			this._ActivityTemplates = new EntitySet<ActivityTemplate>(new Action<ActivityTemplate>(this.attach_ActivityTemplates), new Action<ActivityTemplate>(this.detach_ActivityTemplates));
			this._EmailTemplates = new EntitySet<EmailTemplate>(new Action<EmailTemplate>(this.attach_EmailTemplates), new Action<EmailTemplate>(this.detach_EmailTemplates));
			this._Activities = new EntitySet<Activity>(new Action<Activity>(this.attach_Activities), new Action<Activity>(this.detach_Activities));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Meno", DbType="VarChar(30)")]
		public string Meno
		{
			get
			{
				return this._Meno;
			}
			set
			{
				if ((this._Meno != value))
				{
					this.OnMenoChanging(value);
					this.SendPropertyChanging();
					this._Meno = value;
					this.SendPropertyChanged("Meno");
					this.OnMenoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heslo", DbType="VarChar(20)")]
		public string Heslo
		{
			get
			{
				return this._Heslo;
			}
			set
			{
				if ((this._Heslo != value))
				{
					this.OnHesloChanging(value);
					this.SendPropertyChanging();
					this._Heslo = value;
					this.SendPropertyChanged("Heslo");
					this.OnHesloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApiKey", DbType="VarChar(50)")]
		public string ApiKey
		{
			get
			{
				return this._ApiKey;
			}
			set
			{
				if ((this._ApiKey != value))
				{
					this.OnApiKeyChanging(value);
					this.SendPropertyChanging();
					this._ApiKey = value;
					this.SendPropertyChanged("ApiKey");
					this.OnApiKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_StudentSkupina", Storage="_StudentSkupinas", ThisKey="Id", OtherKey="Id_User")]
		public EntitySet<StudentSkupina> StudentSkupinas
		{
			get
			{
				return this._StudentSkupinas;
			}
			set
			{
				this._StudentSkupinas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_ActivityTemplate", Storage="_ActivityTemplates", ThisKey="Id", OtherKey="IdUser")]
		public EntitySet<ActivityTemplate> ActivityTemplates
		{
			get
			{
				return this._ActivityTemplates;
			}
			set
			{
				this._ActivityTemplates.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_EmailTemplate", Storage="_EmailTemplates", ThisKey="Id", OtherKey="IdUser")]
		public EntitySet<EmailTemplate> EmailTemplates
		{
			get
			{
				return this._EmailTemplates;
			}
			set
			{
				this._EmailTemplates.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Activity", Storage="_Activities", ThisKey="Id", OtherKey="IdUser")]
		public EntitySet<Activity> Activities
		{
			get
			{
				return this._Activities;
			}
			set
			{
				this._Activities.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StudentSkupinas(StudentSkupina entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_StudentSkupinas(StudentSkupina entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_ActivityTemplates(ActivityTemplate entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_ActivityTemplates(ActivityTemplate entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_EmailTemplates(EmailTemplate entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_EmailTemplates(EmailTemplate entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_Activities(Activity entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Activities(Activity entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student")]
	public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Meno;
		
		private string _Priezvisko;
		
		private string _Email;
		
		private string _Email_UCM;
		
		private string _ISIC;
		
		private int _Rocnik;
		
		private string _Forma;
		
		private string _ID_Kruzok;
		
		private string _Stud_program;
		
		private int _ID_stud_skupina;
		
		private EntitySet<AttendanceStud> _AttendanceStuds;
		
		private EntitySet<Activity> _Activities;
		
		private EntitySet<Task> _Tasks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMenoChanging(string value);
    partial void OnMenoChanged();
    partial void OnPriezviskoChanging(string value);
    partial void OnPriezviskoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnEmail_UCMChanging(string value);
    partial void OnEmail_UCMChanged();
    partial void OnISICChanging(string value);
    partial void OnISICChanged();
    partial void OnRocnikChanging(int value);
    partial void OnRocnikChanged();
    partial void OnFormaChanging(string value);
    partial void OnFormaChanged();
    partial void OnID_KruzokChanging(string value);
    partial void OnID_KruzokChanged();
    partial void OnStud_programChanging(string value);
    partial void OnStud_programChanged();
    partial void OnID_stud_skupinaChanging(int value);
    partial void OnID_stud_skupinaChanged();
    #endregion
		
		public Student()
		{
			this._AttendanceStuds = new EntitySet<AttendanceStud>(new Action<AttendanceStud>(this.attach_AttendanceStuds), new Action<AttendanceStud>(this.detach_AttendanceStuds));
			this._Activities = new EntitySet<Activity>(new Action<Activity>(this.attach_Activities), new Action<Activity>(this.detach_Activities));
			this._Tasks = new EntitySet<Task>(new Action<Task>(this.attach_Tasks), new Action<Task>(this.detach_Tasks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Meno", DbType="NChar(25) NOT NULL", CanBeNull=false)]
		public string Meno
		{
			get
			{
				return this._Meno;
			}
			set
			{
				if ((this._Meno != value))
				{
					this.OnMenoChanging(value);
					this.SendPropertyChanging();
					this._Meno = value;
					this.SendPropertyChanged("Meno");
					this.OnMenoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priezvisko", DbType="NChar(35) NOT NULL", CanBeNull=false)]
		public string Priezvisko
		{
			get
			{
				return this._Priezvisko;
			}
			set
			{
				if ((this._Priezvisko != value))
				{
					this.OnPriezviskoChanging(value);
					this.SendPropertyChanging();
					this._Priezvisko = value;
					this.SendPropertyChanged("Priezvisko");
					this.OnPriezviskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(45) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_UCM", DbType="NChar(50)")]
		public string Email_UCM
		{
			get
			{
				return this._Email_UCM;
			}
			set
			{
				if ((this._Email_UCM != value))
				{
					this.OnEmail_UCMChanging(value);
					this.SendPropertyChanging();
					this._Email_UCM = value;
					this.SendPropertyChanged("Email_UCM");
					this.OnEmail_UCMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISIC", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string ISIC
		{
			get
			{
				return this._ISIC;
			}
			set
			{
				if ((this._ISIC != value))
				{
					this.OnISICChanging(value);
					this.SendPropertyChanging();
					this._ISIC = value;
					this.SendPropertyChanged("ISIC");
					this.OnISICChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rocnik", DbType="Int NOT NULL")]
		public int Rocnik
		{
			get
			{
				return this._Rocnik;
			}
			set
			{
				if ((this._Rocnik != value))
				{
					this.OnRocnikChanging(value);
					this.SendPropertyChanging();
					this._Rocnik = value;
					this.SendPropertyChanged("Rocnik");
					this.OnRocnikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Forma", DbType="NChar(7) NOT NULL", CanBeNull=false)]
		public string Forma
		{
			get
			{
				return this._Forma;
			}
			set
			{
				if ((this._Forma != value))
				{
					this.OnFormaChanging(value);
					this.SendPropertyChanging();
					this._Forma = value;
					this.SendPropertyChanged("Forma");
					this.OnFormaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Kruzok", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string ID_Kruzok
		{
			get
			{
				return this._ID_Kruzok;
			}
			set
			{
				if ((this._ID_Kruzok != value))
				{
					this.OnID_KruzokChanging(value);
					this.SendPropertyChanging();
					this._ID_Kruzok = value;
					this.SendPropertyChanged("ID_Kruzok");
					this.OnID_KruzokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stud_program", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Stud_program
		{
			get
			{
				return this._Stud_program;
			}
			set
			{
				if ((this._Stud_program != value))
				{
					this.OnStud_programChanging(value);
					this.SendPropertyChanging();
					this._Stud_program = value;
					this.SendPropertyChanged("Stud_program");
					this.OnStud_programChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_stud_skupina", DbType="Int NOT NULL")]
		public int ID_stud_skupina
		{
			get
			{
				return this._ID_stud_skupina;
			}
			set
			{
				if ((this._ID_stud_skupina != value))
				{
					this.OnID_stud_skupinaChanging(value);
					this.SendPropertyChanging();
					this._ID_stud_skupina = value;
					this.SendPropertyChanged("ID_stud_skupina");
					this.OnID_stud_skupinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_AttendanceStud", Storage="_AttendanceStuds", ThisKey="Id", OtherKey="IDStudent")]
		public EntitySet<AttendanceStud> AttendanceStuds
		{
			get
			{
				return this._AttendanceStuds;
			}
			set
			{
				this._AttendanceStuds.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Activity", Storage="_Activities", ThisKey="Id", OtherKey="IdStudent")]
		public EntitySet<Activity> Activities
		{
			get
			{
				return this._Activities;
			}
			set
			{
				this._Activities.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Task", Storage="_Tasks", ThisKey="Id", OtherKey="IdStudent")]
		public EntitySet<Task> Tasks
		{
			get
			{
				return this._Tasks;
			}
			set
			{
				this._Tasks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AttendanceStuds(AttendanceStud entity)
		{
			this.SendPropertyChanging();
			entity.Student = this;
		}
		
		private void detach_AttendanceStuds(AttendanceStud entity)
		{
			this.SendPropertyChanging();
			entity.Student = null;
		}
		
		private void attach_Activities(Activity entity)
		{
			this.SendPropertyChanging();
			entity.Student = this;
		}
		
		private void detach_Activities(Activity entity)
		{
			this.SendPropertyChanging();
			entity.Student = null;
		}
		
		private void attach_Tasks(Task entity)
		{
			this.SendPropertyChanging();
			entity.Student = this;
		}
		
		private void detach_Tasks(Task entity)
		{
			this.SendPropertyChanging();
			entity.Student = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StudentSkupina")]
	public partial class StudentSkupina : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nazov;
		
		private string _Forma;
		
		private int _Id_User;
		
		private EntitySet<AttendanceStud> _AttendanceStuds;
		
		private EntitySet<Activity> _Activities;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNazovChanging(string value);
    partial void OnNazovChanged();
    partial void OnFormaChanging(string value);
    partial void OnFormaChanged();
    partial void OnId_UserChanging(int value);
    partial void OnId_UserChanged();
    #endregion
		
		public StudentSkupina()
		{
			this._AttendanceStuds = new EntitySet<AttendanceStud>(new Action<AttendanceStud>(this.attach_AttendanceStuds), new Action<AttendanceStud>(this.detach_AttendanceStuds));
			this._Activities = new EntitySet<Activity>(new Action<Activity>(this.attach_Activities), new Action<Activity>(this.detach_Activities));
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazov", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nazov
		{
			get
			{
				return this._Nazov;
			}
			set
			{
				if ((this._Nazov != value))
				{
					this.OnNazovChanging(value);
					this.SendPropertyChanging();
					this._Nazov = value;
					this.SendPropertyChanged("Nazov");
					this.OnNazovChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Forma", DbType="NChar(7) NOT NULL", CanBeNull=false)]
		public string Forma
		{
			get
			{
				return this._Forma;
			}
			set
			{
				if ((this._Forma != value))
				{
					this.OnFormaChanging(value);
					this.SendPropertyChanging();
					this._Forma = value;
					this.SendPropertyChanged("Forma");
					this.OnFormaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_User", DbType="Int NOT NULL")]
		public int Id_User
		{
			get
			{
				return this._Id_User;
			}
			set
			{
				if ((this._Id_User != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_UserChanging(value);
					this.SendPropertyChanging();
					this._Id_User = value;
					this.SendPropertyChanged("Id_User");
					this.OnId_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StudentSkupina_AttendanceStud", Storage="_AttendanceStuds", ThisKey="Id", OtherKey="IDSkupina")]
		public EntitySet<AttendanceStud> AttendanceStuds
		{
			get
			{
				return this._AttendanceStuds;
			}
			set
			{
				this._AttendanceStuds.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StudentSkupina_Activity", Storage="_Activities", ThisKey="Id", OtherKey="IdSkupina")]
		public EntitySet<Activity> Activities
		{
			get
			{
				return this._Activities;
			}
			set
			{
				this._Activities.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_StudentSkupina", Storage="_User", ThisKey="Id_User", OtherKey="Id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.StudentSkupinas.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.StudentSkupinas.Add(this);
						this._Id_User = value.Id;
					}
					else
					{
						this._Id_User = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AttendanceStuds(AttendanceStud entity)
		{
			this.SendPropertyChanging();
			entity.StudentSkupina = this;
		}
		
		private void detach_AttendanceStuds(AttendanceStud entity)
		{
			this.SendPropertyChanging();
			entity.StudentSkupina = null;
		}
		
		private void attach_Activities(Activity entity)
		{
			this.SendPropertyChanging();
			entity.StudentSkupina = this;
		}
		
		private void detach_Activities(Activity entity)
		{
			this.SendPropertyChanging();
			entity.StudentSkupina = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaskTemplate")]
	public partial class TaskTemplate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TaskName;
		
		private double _MaxPts;
		
		private int _IdActivityTemplate;
		
		private EntityRef<ActivityTemplate> _ActivityTemplate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTaskNameChanging(string value);
    partial void OnTaskNameChanged();
    partial void OnMaxPtsChanging(double value);
    partial void OnMaxPtsChanged();
    partial void OnIdActivityTemplateChanging(int value);
    partial void OnIdActivityTemplateChanged();
    #endregion
		
		public TaskTemplate()
		{
			this._ActivityTemplate = default(EntityRef<ActivityTemplate>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TaskName
		{
			get
			{
				return this._TaskName;
			}
			set
			{
				if ((this._TaskName != value))
				{
					this.OnTaskNameChanging(value);
					this.SendPropertyChanging();
					this._TaskName = value;
					this.SendPropertyChanged("TaskName");
					this.OnTaskNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxPts", DbType="Float NOT NULL")]
		public double MaxPts
		{
			get
			{
				return this._MaxPts;
			}
			set
			{
				if ((this._MaxPts != value))
				{
					this.OnMaxPtsChanging(value);
					this.SendPropertyChanging();
					this._MaxPts = value;
					this.SendPropertyChanged("MaxPts");
					this.OnMaxPtsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdActivityTemplate", DbType="Int NOT NULL")]
		public int IdActivityTemplate
		{
			get
			{
				return this._IdActivityTemplate;
			}
			set
			{
				if ((this._IdActivityTemplate != value))
				{
					if (this._ActivityTemplate.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdActivityTemplateChanging(value);
					this.SendPropertyChanging();
					this._IdActivityTemplate = value;
					this.SendPropertyChanged("IdActivityTemplate");
					this.OnIdActivityTemplateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ActivityTemplate_TaskTemplate", Storage="_ActivityTemplate", ThisKey="IdActivityTemplate", OtherKey="Id", IsForeignKey=true)]
		public ActivityTemplate ActivityTemplate
		{
			get
			{
				return this._ActivityTemplate.Entity;
			}
			set
			{
				ActivityTemplate previousValue = this._ActivityTemplate.Entity;
				if (((previousValue != value) 
							|| (this._ActivityTemplate.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ActivityTemplate.Entity = null;
						previousValue.TaskTemplates.Remove(this);
					}
					this._ActivityTemplate.Entity = value;
					if ((value != null))
					{
						value.TaskTemplates.Add(this);
						this._IdActivityTemplate = value.Id;
					}
					else
					{
						this._IdActivityTemplate = default(int);
					}
					this.SendPropertyChanged("ActivityTemplate");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ActivityTemplate")]
	public partial class ActivityTemplate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ActivityName;
		
		private double _MaxPoints;
		
		private int _IdUser;
		
		private System.Nullable<int> _FirstRem;
		
		private System.Nullable<int> _SecondRem;
		
		private System.Nullable<int> _ThirdRem;
		
		private EntitySet<TaskTemplate> _TaskTemplates;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnActivityNameChanging(string value);
    partial void OnActivityNameChanged();
    partial void OnMaxPointsChanging(double value);
    partial void OnMaxPointsChanged();
    partial void OnIdUserChanging(int value);
    partial void OnIdUserChanged();
    partial void OnFirstRemChanging(System.Nullable<int> value);
    partial void OnFirstRemChanged();
    partial void OnSecondRemChanging(System.Nullable<int> value);
    partial void OnSecondRemChanged();
    partial void OnThirdRemChanging(System.Nullable<int> value);
    partial void OnThirdRemChanged();
    #endregion
		
		public ActivityTemplate()
		{
			this._TaskTemplates = new EntitySet<TaskTemplate>(new Action<TaskTemplate>(this.attach_TaskTemplates), new Action<TaskTemplate>(this.detach_TaskTemplates));
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityName", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string ActivityName
		{
			get
			{
				return this._ActivityName;
			}
			set
			{
				if ((this._ActivityName != value))
				{
					this.OnActivityNameChanging(value);
					this.SendPropertyChanging();
					this._ActivityName = value;
					this.SendPropertyChanged("ActivityName");
					this.OnActivityNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxPoints", DbType="Float NOT NULL")]
		public double MaxPoints
		{
			get
			{
				return this._MaxPoints;
			}
			set
			{
				if ((this._MaxPoints != value))
				{
					this.OnMaxPointsChanging(value);
					this.SendPropertyChanging();
					this._MaxPoints = value;
					this.SendPropertyChanged("MaxPoints");
					this.OnMaxPointsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUser", DbType="Int NOT NULL")]
		public int IdUser
		{
			get
			{
				return this._IdUser;
			}
			set
			{
				if ((this._IdUser != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUserChanging(value);
					this.SendPropertyChanging();
					this._IdUser = value;
					this.SendPropertyChanged("IdUser");
					this.OnIdUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstRem", DbType="Int")]
		public System.Nullable<int> FirstRem
		{
			get
			{
				return this._FirstRem;
			}
			set
			{
				if ((this._FirstRem != value))
				{
					this.OnFirstRemChanging(value);
					this.SendPropertyChanging();
					this._FirstRem = value;
					this.SendPropertyChanged("FirstRem");
					this.OnFirstRemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondRem", DbType="Int")]
		public System.Nullable<int> SecondRem
		{
			get
			{
				return this._SecondRem;
			}
			set
			{
				if ((this._SecondRem != value))
				{
					this.OnSecondRemChanging(value);
					this.SendPropertyChanging();
					this._SecondRem = value;
					this.SendPropertyChanged("SecondRem");
					this.OnSecondRemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThirdRem", DbType="Int")]
		public System.Nullable<int> ThirdRem
		{
			get
			{
				return this._ThirdRem;
			}
			set
			{
				if ((this._ThirdRem != value))
				{
					this.OnThirdRemChanging(value);
					this.SendPropertyChanging();
					this._ThirdRem = value;
					this.SendPropertyChanged("ThirdRem");
					this.OnThirdRemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ActivityTemplate_TaskTemplate", Storage="_TaskTemplates", ThisKey="Id", OtherKey="IdActivityTemplate")]
		public EntitySet<TaskTemplate> TaskTemplates
		{
			get
			{
				return this._TaskTemplates;
			}
			set
			{
				this._TaskTemplates.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_ActivityTemplate", Storage="_User", ThisKey="IdUser", OtherKey="Id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.ActivityTemplates.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.ActivityTemplates.Add(this);
						this._IdUser = value.Id;
					}
					else
					{
						this._IdUser = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaskTemplates(TaskTemplate entity)
		{
			this.SendPropertyChanging();
			entity.ActivityTemplate = this;
		}
		
		private void detach_TaskTemplates(TaskTemplate entity)
		{
			this.SendPropertyChanging();
			entity.ActivityTemplate = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmailTemplate")]
	public partial class EmailTemplate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _EmailSubject;
		
		private string _EmailContent;
		
		private int _IdUser;
		
		private string _EmailTemplateName;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnEmailSubjectChanging(string value);
    partial void OnEmailSubjectChanged();
    partial void OnEmailContentChanging(string value);
    partial void OnEmailContentChanged();
    partial void OnIdUserChanging(int value);
    partial void OnIdUserChanged();
    partial void OnEmailTemplateNameChanging(string value);
    partial void OnEmailTemplateNameChanged();
    #endregion
		
		public EmailTemplate()
		{
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailSubject", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EmailSubject
		{
			get
			{
				return this._EmailSubject;
			}
			set
			{
				if ((this._EmailSubject != value))
				{
					this.OnEmailSubjectChanging(value);
					this.SendPropertyChanging();
					this._EmailSubject = value;
					this.SendPropertyChanged("EmailSubject");
					this.OnEmailSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailContent", DbType="NChar(1000) NOT NULL", CanBeNull=false)]
		public string EmailContent
		{
			get
			{
				return this._EmailContent;
			}
			set
			{
				if ((this._EmailContent != value))
				{
					this.OnEmailContentChanging(value);
					this.SendPropertyChanging();
					this._EmailContent = value;
					this.SendPropertyChanged("EmailContent");
					this.OnEmailContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUser", DbType="Int NOT NULL")]
		public int IdUser
		{
			get
			{
				return this._IdUser;
			}
			set
			{
				if ((this._IdUser != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUserChanging(value);
					this.SendPropertyChanging();
					this._IdUser = value;
					this.SendPropertyChanged("IdUser");
					this.OnIdUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTemplateName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailTemplateName
		{
			get
			{
				return this._EmailTemplateName;
			}
			set
			{
				if ((this._EmailTemplateName != value))
				{
					this.OnEmailTemplateNameChanging(value);
					this.SendPropertyChanging();
					this._EmailTemplateName = value;
					this.SendPropertyChanged("EmailTemplateName");
					this.OnEmailTemplateNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_EmailTemplate", Storage="_User", ThisKey="IdUser", OtherKey="Id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.EmailTemplates.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.EmailTemplates.Add(this);
						this._IdUser = value.Id;
					}
					else
					{
						this._IdUser = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Activity")]
	public partial class Activity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ActivityName;
		
		private int _IdStudent;
		
		private int _IdUser;
		
		private int _IdSkupina;
		
		private System.DateTime _Deadline;
		
		private double _MaxPoints;
		
		private bool _EmailSendingActive;
		
		private System.Nullable<int> _Hodnotenie;
		
		private System.Nullable<bool> _Hodnotene;
		
		private System.Nullable<int> _DaysBeforeDeadline;
		
		private System.Nullable<int> _IdFirstRem;
		
		private System.Nullable<int> _IdSecRem;
		
		private System.Nullable<int> _IdThirdRem;
		
		private System.Nullable<bool> _SendFirst;
		
		private System.Nullable<bool> _SendSecond;
		
		private System.Nullable<bool> _SendThird;
		
		private EntitySet<Task> _Tasks;
		
		private EntityRef<User> _User;
		
		private EntityRef<StudentSkupina> _StudentSkupina;
		
		private EntityRef<Student> _Student;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnActivityNameChanging(string value);
    partial void OnActivityNameChanged();
    partial void OnIdStudentChanging(int value);
    partial void OnIdStudentChanged();
    partial void OnIdUserChanging(int value);
    partial void OnIdUserChanged();
    partial void OnIdSkupinaChanging(int value);
    partial void OnIdSkupinaChanged();
    partial void OnDeadlineChanging(System.DateTime value);
    partial void OnDeadlineChanged();
    partial void OnMaxPointsChanging(double value);
    partial void OnMaxPointsChanged();
    partial void OnEmailSendingActiveChanging(bool value);
    partial void OnEmailSendingActiveChanged();
    partial void OnHodnotenieChanging(System.Nullable<int> value);
    partial void OnHodnotenieChanged();
    partial void OnHodnoteneChanging(System.Nullable<bool> value);
    partial void OnHodnoteneChanged();
    partial void OnDaysBeforeDeadlineChanging(System.Nullable<int> value);
    partial void OnDaysBeforeDeadlineChanged();
    partial void OnIdFirstRemChanging(System.Nullable<int> value);
    partial void OnIdFirstRemChanged();
    partial void OnIdSecRemChanging(System.Nullable<int> value);
    partial void OnIdSecRemChanged();
    partial void OnIdThirdRemChanging(System.Nullable<int> value);
    partial void OnIdThirdRemChanged();
    partial void OnSendFirstChanging(System.Nullable<bool> value);
    partial void OnSendFirstChanged();
    partial void OnSendSecondChanging(System.Nullable<bool> value);
    partial void OnSendSecondChanged();
    partial void OnSendThirdChanging(System.Nullable<bool> value);
    partial void OnSendThirdChanged();
    #endregion
		
		public Activity()
		{
			this._Tasks = new EntitySet<Task>(new Action<Task>(this.attach_Tasks), new Action<Task>(this.detach_Tasks));
			this._User = default(EntityRef<User>);
			this._StudentSkupina = default(EntityRef<StudentSkupina>);
			this._Student = default(EntityRef<Student>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ActivityName
		{
			get
			{
				return this._ActivityName;
			}
			set
			{
				if ((this._ActivityName != value))
				{
					this.OnActivityNameChanging(value);
					this.SendPropertyChanging();
					this._ActivityName = value;
					this.SendPropertyChanged("ActivityName");
					this.OnActivityNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdStudent", DbType="Int NOT NULL")]
		public int IdStudent
		{
			get
			{
				return this._IdStudent;
			}
			set
			{
				if ((this._IdStudent != value))
				{
					if (this._Student.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdStudentChanging(value);
					this.SendPropertyChanging();
					this._IdStudent = value;
					this.SendPropertyChanged("IdStudent");
					this.OnIdStudentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUser", DbType="Int NOT NULL")]
		public int IdUser
		{
			get
			{
				return this._IdUser;
			}
			set
			{
				if ((this._IdUser != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUserChanging(value);
					this.SendPropertyChanging();
					this._IdUser = value;
					this.SendPropertyChanged("IdUser");
					this.OnIdUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSkupina", DbType="Int NOT NULL")]
		public int IdSkupina
		{
			get
			{
				return this._IdSkupina;
			}
			set
			{
				if ((this._IdSkupina != value))
				{
					if (this._StudentSkupina.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdSkupinaChanging(value);
					this.SendPropertyChanging();
					this._IdSkupina = value;
					this.SendPropertyChanged("IdSkupina");
					this.OnIdSkupinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deadline", DbType="DateTime NOT NULL")]
		public System.DateTime Deadline
		{
			get
			{
				return this._Deadline;
			}
			set
			{
				if ((this._Deadline != value))
				{
					this.OnDeadlineChanging(value);
					this.SendPropertyChanging();
					this._Deadline = value;
					this.SendPropertyChanged("Deadline");
					this.OnDeadlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxPoints", DbType="Float NOT NULL")]
		public double MaxPoints
		{
			get
			{
				return this._MaxPoints;
			}
			set
			{
				if ((this._MaxPoints != value))
				{
					this.OnMaxPointsChanging(value);
					this.SendPropertyChanging();
					this._MaxPoints = value;
					this.SendPropertyChanged("MaxPoints");
					this.OnMaxPointsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailSendingActive", DbType="Bit NOT NULL")]
		public bool EmailSendingActive
		{
			get
			{
				return this._EmailSendingActive;
			}
			set
			{
				if ((this._EmailSendingActive != value))
				{
					this.OnEmailSendingActiveChanging(value);
					this.SendPropertyChanging();
					this._EmailSendingActive = value;
					this.SendPropertyChanged("EmailSendingActive");
					this.OnEmailSendingActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hodnotenie", DbType="Int")]
		public System.Nullable<int> Hodnotenie
		{
			get
			{
				return this._Hodnotenie;
			}
			set
			{
				if ((this._Hodnotenie != value))
				{
					this.OnHodnotenieChanging(value);
					this.SendPropertyChanging();
					this._Hodnotenie = value;
					this.SendPropertyChanged("Hodnotenie");
					this.OnHodnotenieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hodnotene", DbType="Bit")]
		public System.Nullable<bool> Hodnotene
		{
			get
			{
				return this._Hodnotene;
			}
			set
			{
				if ((this._Hodnotene != value))
				{
					this.OnHodnoteneChanging(value);
					this.SendPropertyChanging();
					this._Hodnotene = value;
					this.SendPropertyChanged("Hodnotene");
					this.OnHodnoteneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaysBeforeDeadline", DbType="Int")]
		public System.Nullable<int> DaysBeforeDeadline
		{
			get
			{
				return this._DaysBeforeDeadline;
			}
			set
			{
				if ((this._DaysBeforeDeadline != value))
				{
					this.OnDaysBeforeDeadlineChanging(value);
					this.SendPropertyChanging();
					this._DaysBeforeDeadline = value;
					this.SendPropertyChanged("DaysBeforeDeadline");
					this.OnDaysBeforeDeadlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFirstRem", DbType="Int")]
		public System.Nullable<int> IdFirstRem
		{
			get
			{
				return this._IdFirstRem;
			}
			set
			{
				if ((this._IdFirstRem != value))
				{
					this.OnIdFirstRemChanging(value);
					this.SendPropertyChanging();
					this._IdFirstRem = value;
					this.SendPropertyChanged("IdFirstRem");
					this.OnIdFirstRemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSecRem", DbType="Int")]
		public System.Nullable<int> IdSecRem
		{
			get
			{
				return this._IdSecRem;
			}
			set
			{
				if ((this._IdSecRem != value))
				{
					this.OnIdSecRemChanging(value);
					this.SendPropertyChanging();
					this._IdSecRem = value;
					this.SendPropertyChanged("IdSecRem");
					this.OnIdSecRemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdThirdRem", DbType="Int")]
		public System.Nullable<int> IdThirdRem
		{
			get
			{
				return this._IdThirdRem;
			}
			set
			{
				if ((this._IdThirdRem != value))
				{
					this.OnIdThirdRemChanging(value);
					this.SendPropertyChanging();
					this._IdThirdRem = value;
					this.SendPropertyChanged("IdThirdRem");
					this.OnIdThirdRemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendFirst", DbType="Bit")]
		public System.Nullable<bool> SendFirst
		{
			get
			{
				return this._SendFirst;
			}
			set
			{
				if ((this._SendFirst != value))
				{
					this.OnSendFirstChanging(value);
					this.SendPropertyChanging();
					this._SendFirst = value;
					this.SendPropertyChanged("SendFirst");
					this.OnSendFirstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendSecond", DbType="Bit")]
		public System.Nullable<bool> SendSecond
		{
			get
			{
				return this._SendSecond;
			}
			set
			{
				if ((this._SendSecond != value))
				{
					this.OnSendSecondChanging(value);
					this.SendPropertyChanging();
					this._SendSecond = value;
					this.SendPropertyChanged("SendSecond");
					this.OnSendSecondChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendThird", DbType="Bit")]
		public System.Nullable<bool> SendThird
		{
			get
			{
				return this._SendThird;
			}
			set
			{
				if ((this._SendThird != value))
				{
					this.OnSendThirdChanging(value);
					this.SendPropertyChanging();
					this._SendThird = value;
					this.SendPropertyChanged("SendThird");
					this.OnSendThirdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Activity_Task", Storage="_Tasks", ThisKey="Id", OtherKey="IdActivity")]
		public EntitySet<Task> Tasks
		{
			get
			{
				return this._Tasks;
			}
			set
			{
				this._Tasks.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Activity", Storage="_User", ThisKey="IdUser", OtherKey="Id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Activities.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Activities.Add(this);
						this._IdUser = value.Id;
					}
					else
					{
						this._IdUser = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StudentSkupina_Activity", Storage="_StudentSkupina", ThisKey="IdSkupina", OtherKey="Id", IsForeignKey=true)]
		public StudentSkupina StudentSkupina
		{
			get
			{
				return this._StudentSkupina.Entity;
			}
			set
			{
				StudentSkupina previousValue = this._StudentSkupina.Entity;
				if (((previousValue != value) 
							|| (this._StudentSkupina.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StudentSkupina.Entity = null;
						previousValue.Activities.Remove(this);
					}
					this._StudentSkupina.Entity = value;
					if ((value != null))
					{
						value.Activities.Add(this);
						this._IdSkupina = value.Id;
					}
					else
					{
						this._IdSkupina = default(int);
					}
					this.SendPropertyChanged("StudentSkupina");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Activity", Storage="_Student", ThisKey="IdStudent", OtherKey="Id", IsForeignKey=true)]
		public Student Student
		{
			get
			{
				return this._Student.Entity;
			}
			set
			{
				Student previousValue = this._Student.Entity;
				if (((previousValue != value) 
							|| (this._Student.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student.Entity = null;
						previousValue.Activities.Remove(this);
					}
					this._Student.Entity = value;
					if ((value != null))
					{
						value.Activities.Add(this);
						this._IdStudent = value.Id;
					}
					else
					{
						this._IdStudent = default(int);
					}
					this.SendPropertyChanged("Student");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tasks(Task entity)
		{
			this.SendPropertyChanging();
			entity.Activity = this;
		}
		
		private void detach_Tasks(Task entity)
		{
			this.SendPropertyChanging();
			entity.Activity = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Task")]
	public partial class Task : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TaskName;
		
		private int _IdActivity;
		
		private double _Points;
		
		private int _IdStudent;
		
		private string _Comment;
		
		private System.Nullable<double> _Hodnotenie;
		
		private EntityRef<Activity> _Activity;
		
		private EntityRef<Student> _Student;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTaskNameChanging(string value);
    partial void OnTaskNameChanged();
    partial void OnIdActivityChanging(int value);
    partial void OnIdActivityChanged();
    partial void OnPointsChanging(double value);
    partial void OnPointsChanged();
    partial void OnIdStudentChanging(int value);
    partial void OnIdStudentChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnHodnotenieChanging(System.Nullable<double> value);
    partial void OnHodnotenieChanged();
    #endregion
		
		public Task()
		{
			this._Activity = default(EntityRef<Activity>);
			this._Student = default(EntityRef<Student>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TaskName
		{
			get
			{
				return this._TaskName;
			}
			set
			{
				if ((this._TaskName != value))
				{
					this.OnTaskNameChanging(value);
					this.SendPropertyChanging();
					this._TaskName = value;
					this.SendPropertyChanged("TaskName");
					this.OnTaskNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdActivity", DbType="Int NOT NULL")]
		public int IdActivity
		{
			get
			{
				return this._IdActivity;
			}
			set
			{
				if ((this._IdActivity != value))
				{
					if (this._Activity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdActivityChanging(value);
					this.SendPropertyChanging();
					this._IdActivity = value;
					this.SendPropertyChanged("IdActivity");
					this.OnIdActivityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Points", DbType="Float NOT NULL")]
		public double Points
		{
			get
			{
				return this._Points;
			}
			set
			{
				if ((this._Points != value))
				{
					this.OnPointsChanging(value);
					this.SendPropertyChanging();
					this._Points = value;
					this.SendPropertyChanged("Points");
					this.OnPointsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdStudent", DbType="Int NOT NULL")]
		public int IdStudent
		{
			get
			{
				return this._IdStudent;
			}
			set
			{
				if ((this._IdStudent != value))
				{
					if (this._Student.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdStudentChanging(value);
					this.SendPropertyChanging();
					this._IdStudent = value;
					this.SendPropertyChanged("IdStudent");
					this.OnIdStudentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="VarChar(250)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hodnotenie", DbType="Float")]
		public System.Nullable<double> Hodnotenie
		{
			get
			{
				return this._Hodnotenie;
			}
			set
			{
				if ((this._Hodnotenie != value))
				{
					this.OnHodnotenieChanging(value);
					this.SendPropertyChanging();
					this._Hodnotenie = value;
					this.SendPropertyChanged("Hodnotenie");
					this.OnHodnotenieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Activity_Task", Storage="_Activity", ThisKey="IdActivity", OtherKey="Id", IsForeignKey=true)]
		public Activity Activity
		{
			get
			{
				return this._Activity.Entity;
			}
			set
			{
				Activity previousValue = this._Activity.Entity;
				if (((previousValue != value) 
							|| (this._Activity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Activity.Entity = null;
						previousValue.Tasks.Remove(this);
					}
					this._Activity.Entity = value;
					if ((value != null))
					{
						value.Tasks.Add(this);
						this._IdActivity = value.Id;
					}
					else
					{
						this._IdActivity = default(int);
					}
					this.SendPropertyChanged("Activity");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Task", Storage="_Student", ThisKey="IdStudent", OtherKey="Id", IsForeignKey=true)]
		public Student Student
		{
			get
			{
				return this._Student.Entity;
			}
			set
			{
				Student previousValue = this._Student.Entity;
				if (((previousValue != value) 
							|| (this._Student.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student.Entity = null;
						previousValue.Tasks.Remove(this);
					}
					this._Student.Entity = value;
					if ((value != null))
					{
						value.Tasks.Add(this);
						this._IdStudent = value.Id;
					}
					else
					{
						this._IdStudent = default(int);
					}
					this.SendPropertyChanged("Student");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
